import {existsSync, readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {defineConfig} from 'vitepress';

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url));

/**
 * Sidebar of the API reference, generated by TypeDoc together with the reference
 */
const apiSidebar = existsSync(path('../api/typedoc-sidebar.json'))
  ? JSON.parse(readFileSync(path('../api/typedoc-sidebar.json'), 'utf8'))
  : [];

export default defineConfig({
  lang: 'en-US',
  title: 'Tick-Knock',
  description: 'Small and powerful, type-safe and easy-to-use Entity-Component-System library written in TypeScript',
  base: '/tick-knock/',
  cleanUrls: true,
  lastUpdated: true,
  themeConfig: {
    nav: [
      {text: 'Guide', link: '/guide/', activeMatch: '/guide/'},
      {text: 'Tutorials', link: '/tutorials/', activeMatch: '/tutorials/'},
      {text: 'Decisions', link: '/decisions/', activeMatch: '/decisions/'},
      {text: 'Examples', link: '/examples/', activeMatch: '/examples/'},
      {text: 'API', link: '/api/', activeMatch: '/api/'},
      {text: 'Benchmarks', link: '/benchmarks'},
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Getting started',
          items: [
            {text: 'Introduction', link: '/guide/'},
            {text: 'Installing', link: '/guide/installing'},
            {text: 'What\'s new in 5.0', link: '/guide/whats-new'},
            {text: 'Migrating from 4.x', link: '/guide/migrating'},
          ],
        },
        {
          text: 'Concepts',
          items: [
            {text: 'Engine', link: '/guide/engine'},
            {text: 'Component', link: '/guide/component'},
            {text: 'Tag', link: '/guide/tag'},
            {text: 'Entity', link: '/guide/entity'},
            {text: 'Query', link: '/guide/query'},
            {text: 'System', link: '/guide/system'},
            {text: 'Built-in systems', link: '/guide/built-in-systems'},
            {text: 'Messages', link: '/guide/messages'},
            {text: 'Snapshot', link: '/guide/snapshot'},
            {text: 'Linked components', link: '/guide/linked-components'},
          ],
        },
        {
          text: 'Going further',
          items: [
            {text: 'Restrictions', link: '/guide/restrictions'},
          ],
        },
      ],
      '/tutorials/': [
        {
          text: 'Tutorials',
          items: [
            {text: 'Overview', link: '/tutorials/'},
            {text: 'Snake', link: '/tutorials/snake'},
            {text: 'Asteroids', link: '/tutorials/asteroids'},
            {text: 'Bullet hell', link: '/tutorials/bullet-hell'},
            {text: 'Tower defense', link: '/tutorials/tower-defense'},
          ],
        },
      ],
      '/decisions/': [
        {
          text: 'Decisions',
          items: [
            {text: 'Overview', link: '/decisions/'},
            {text: 'Component or tag?', link: '/decisions/component-or-tag'},
            {text: 'Which system?', link: '/decisions/which-system'},
            {text: 'Message or component?', link: '/decisions/message-or-component'},
            {text: 'Where to keep game state?', link: '/decisions/game-state'},
            {text: 'Remove the entity or the component?', link: '/decisions/removing'},
            {text: 'Linked components or an array?', link: '/decisions/linked-components'},
            {text: 'Keeping rendering apart', link: '/decisions/rendering'},
            {text: 'Performance', link: '/decisions/performance'},
          ],
        },
      ],
      '/api/': [
        {text: 'API reference', link: '/api/'},
        ...apiSidebar,
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            {text: 'Overview', link: '/examples/'},
            {text: 'Snake', link: '/examples/snake'},
            {text: 'Asteroids', link: '/examples/asteroids'},
            {text: 'Bullet hell', link: '/examples/bullet-hell'},
            {text: 'Tower defense', link: '/examples/tower-defense'},
          ],
        },
      ],
    },
    socialLinks: [
      {icon: 'github', link: 'https://github.com/mayakwd/tick-knock'},
      {icon: 'npm', link: 'https://www.npmjs.com/package/tick-knock'},
    ],
    editLink: {
      pattern: 'https://github.com/mayakwd/tick-knock/edit/develop/site/:path',
    },
    search: {
      provider: 'local',
    },
    // Dates are formatted in the language of the site, not in the locale of the browser
    lastUpdated: {
      formatOptions: {dateStyle: 'medium', forceLocale: true},
    },
    footer: {
      message: 'Released under the MIT License.',
    },
  },
  vite: {
    resolve: {
      alias: {
        // Examples use sources of the library, so the site shows the current version
        'tick-knock': path('../../src/index.ts'),
        '@examples': path('../../examples'),
      },
    },
  },
});
