name: Publish to NPM

on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test-ci

      - name: Pack
        run: yarn pack

  publish-to-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
    needs: build
    steps:
      - name: Publish to NPM
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}